POST http://localhost:5001/users
Content-Type: application/json

{
    "smoke": "all",
    "pet": "all",
    "food": "all"
}

###

POST http://localhost:4001/users
Content-Type: application/json

{
"name": "asd",
"email": "asd",
"pass": "$2b$10$u0ucb3jQODKtQfsGzb.r/uw4DmKyKvLTB5y9lpQYaHjqSKjh3Kd.e",
"smoke": "smoke",
"pet": "pet",
"food": "veg"
}

###

POST http://localhost:3001/users/register
Content-Type: application/json

{
    "email": "asda",
    "pass": "asdq"
}

###

POST http://localhost:3001/users/login
Content-Type: application/json

{
    "name": "Rana",
    "password": "passw"
}